### ISSUE TITLE
A cache file gets truncated and `json.decoder` crashes the app when trying to load it.

### ISSUE THREAD

**Issue by umnovI** [karpetrosyan/hishel#180]
Hi, I've just discovered a weird bug (?)

Hishel for some reason truncates file making it 0 bytes, but doesn't write anything in it. This causes `JSONDecodeError` and crashes the application.
I was running test on my personal project and all of a sudden they started failing.

I'm not sure what caused it and if I can reproduce what created empty files.
But here's the log just in case.

```
INFO:     127.0.0.1:59745 - "GET /api/language/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\api_analytics\fastapi.py", line 85, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\pokemon_project\backend\app.py", line 147, in get_group
    remote_api = await make_request(f"/{endpoint.value}/", pagination, background_tasks=background_tasks)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\pokemon_project\backend\dependencies.py", line 38, in make_request
    data = await fetch_remote(DataForRequest(url=endpoint, query=query), HISHEL_CLIENT, HOST, background_tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\pokemon_project\backend\api.py", line 140, in fetch_remote
    response = await client.get(request_url, timeout=3, params=req.query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1786, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1646, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\httpx\_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\hishel\_async\_transports.py", line 103, in handle_async_request
    stored_data = await self._storage.retrieve(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\hishel\_async\_storages.py", line 131, in retrieve
    return self._serializer.loads(await self._file_manager.read_from(str(response_path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\site-packages\hishel\_serializers.py", line 161, in loads
    full_json = json.loads(data)
                ^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\pokemon_project\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Files:
![image](https://github.com/karpetrosyan/hishel/assets/30232564/f9a8db78-2fe0-4023-a2b3-0096f6870043)

**Comment by karpetrosyan** [comment]
Hi! Thank you for the issue

We need a way to reproduce this.

Can you tell your python/hishel versions?

**Comment by umnovI** [comment]
```
Python 3.12.1
hishel 0.0.22
```
I have a more detailed log. From tests when they started failing. But I don't think I can see what could create an empty file.
https://gist.github.com/umnovI/a48eff66af4343e4bb7b26118186ebb0

**Comment by karpetrosyan** [comment]
I guess yes.
This issue can also occur if you have multiple processes running in the same directory and sharing the same cache.

If such an exception occurs, I believe we could just suppress the decoding failures and destroy the cache; however, decode exceptions are also possible when the cache model is changed in a new version of hishel.

**Comment by umnovI** [comment]
I would guess checking for empty could be enough, no? And returning None for example.

**Comment by karpetrosyan** [comment]
I will accept any of them, both looks good to me.

**Comment by umnovI** [comment]
I was able to reproduce the bug.

![ef2e8a1a3ff93d68f5ed42b2ca498e55 - hishel - Visual Studio Code 2024-02-05 02-45-53](https://github.com/karpetrosyan/hishel/assets/30232564/b1cbe76f-9317-4caf-87bd-90192f9d1929)

Code to reproduce:

```python
import asyncio
import os
from pathlib import Path
from typing import Any

import httpx
import pytest
from httpcore import Request
from pytest_httpx import HTTPXMock

import hishel
from hishel._utils import asleep, generate_key


@pytest.fixture()
async def hishel_client():
    storage = hishel.AsyncFileStorage()
    controller = hishel.Controller(allow_stale=True)
    client = hishel.AsyncCacheClient(
        storage=storage,
        controller=controller,
    )

    async with client:
        yield client


@pytest.mark.parametrize("anyio_backend", ["asyncio"])
async def test_breaking_filestorage(anyio_backend, httpx_mock: HTTPXMock, hishel_client: hishel.AsyncCacheClient):
    async def custom_response(request: httpx.Request):
        await asleep(0.3)
        return httpx.Response(
            status_code=200,
            headers=[
                ("Location", f"{request.url}"),
                ("Cache-Control", "public, max-age=86400, s-maxage=86400"),
                ("Date", "Sun, 04 Feb 2024 21:00:05 GMT"),
            ],
            text="""{
                "count": 1302,
                "next": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                "previous": "null",
                "results": [
                    {"name": "test1", "url": "http://test.loc/"},
                ],
            }""",
        )

    httpx_mock.add_callback(custom_response)

    request = Request(b"GET", "https://test.loc/")
    key = generate_key(request)

    async def err(*args):
        await asleep(2)
        raise BaseException("Error!")

    tasks: list[Any] = [hishel_client.get("https://test.loc/") for i in range(1500)]
    tasks.append(err(None))
    tasks.append(hishel_client.get("https://test.loc/"))

    try:
        async with asyncio.TaskGroup() as tg:
            result = []
            for task in tasks:
                result.append(tg.create_task(task))
    except BaseException:
        filepath = Path(f"./.cache/hishel/{key}")
        assert filepath.is_file()
        assert os.stat(filepath).st_size == 0
```

It might take a few runs, or just one.
You'll need this library: https://github.com/Colin-b/pytest_httpx
Couldn't make it work with ` hishel.MockAsyncTransport()`.
Also couldn't repro with `AnyIO`.
